### ISSUE TITLE
Support connecting to Windows OpenSSH agent over named pipe

### ISSUE THREAD

**Issue by antoineco** [wez/libssh-rs#13]
Windows 11 connects to the built-in OpenSSH agent over a [named pipe](https://learn.microsoft.com/en-us/windows/win32/ipc/named-pipes) (`\\.\pipe\openssh-ssh-agent`).

This doesn't seem supported in `libssh-rs`.
The syntax `IdentityAgent \\.\pipe\openssh-ssh-agent` — which works with Window's built-in OpenSSH client (`OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3`) — is recognized as a UNIX socket instead of a Windows named pipe, at least in WezTerm:

```
libssh::ssh_socket_unix   > Error from connect(\\.\pipe\openssh-ssh-agent): No such file or directory
```

Ref.
- https://github.com/wez/wezterm/discussions/3772
- https://github.com/PowerShell/openssh-portable

**Comment by wez** [comment]
This needs support from the underlying ssh library. Please file an issue in the upstream:
https://gitlab.com/libssh/libssh-mirror/-/issues

**Comment by antoineco** [comment]
I assumed too fast that libssh already supported that because v0.10.0 claims to have "support for ssh-agent on Windows" (cf. CHANGELOG). I'll dig upstream 👍
